# Generated by Django 3.0.8 on 2021-10-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20211017_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
