# Generated by Django 3.0.8 on 2021-10-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20211017_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
