# Generated by Django 3.0.8 on 2021-10-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
