# Generated by Django 3.0.8 on 2021-10-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
