# Generated by Django 3.0.8 on 2021-10-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20211030_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='like_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, max_length=2),
        ),
    ]
