# Generated by Django 3.0.8 on 2021-10-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20211030_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
