# Generated by Django 3.0.8 on 2021-10-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_suggest',
            field=models.BooleanField(default=False),
        ),
    ]
