# Generated by Django 3.0.8 on 2021-11-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='books/%Y/%m/%d'),
        ),
    ]
