# Generated by Django 3.0.8 on 2021-12-11 09:02

import apps.vadmin.op_drf.fields
import apps.vadmin.system.models.save_file
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='Description', null=True, verbose_name='Description')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='The record was last modified by', max_length=255, null=True, verbose_name='editor')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Data attribution department')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('dictName', models.CharField(max_length=64, verbose_name='Dictionary name')),
                ('dictType', models.CharField(max_length=64, verbose_name='Dictionary type')),
                ('status', models.CharField(max_length=8, verbose_name='Dictionary status')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='Remark')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='user_create')),
            ],
            options={
                'verbose_name': 'Dictionary management',
                'verbose_name_plural': 'Dictionary management',
            },
        ),
        migrations.CreateModel(
            name='MessagePush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='Description', null=True, verbose_name='Description')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='The record was last modified by', max_length=255, null=True, verbose_name='editor')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Data attribution department')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=128, verbose_name='Notification title')),
                ('content', models.TextField(verbose_name='Notification content')),
                ('message_type', models.CharField(max_length=8, verbose_name='Notification type')),
                ('is_reviewed', models.BooleanField(default=True, verbose_name='Whether to review')),
                ('status', models.CharField(max_length=8, verbose_name='Notification status')),
                ('to_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='Jump path')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='user_create')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcement',
            },
        ),
        migrations.CreateModel(
            name='SaveFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='Description', null=True, verbose_name='Description')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='The record was last modified by', max_length=255, null=True, verbose_name='editor')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Data attribution department')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='File name')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Type')),
                ('size', models.CharField(blank=True, max_length=64, null=True, verbose_name='Size')),
                ('address', models.CharField(blank=True, max_length=16, null=True, verbose_name='Address')),
                ('source', models.CharField(blank=True, max_length=16, null=True, verbose_name='Source')),
                ('oss_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='OSS')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('file', models.FileField(upload_to=apps.vadmin.system.models.save_file.files_path, verbose_name='URL')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='user_create')),
            ],
            options={
                'verbose_name': 'SaveFile',
                'verbose_name_plural': 'SaveFile',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='Description', null=True, verbose_name='Description')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='The record was last modified by', max_length=255, null=True, verbose_name='editor')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Data attribution department')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('request_modular', models.CharField(blank=True, max_length=64, null=True, verbose_name='Request module')),
                ('request_path', models.CharField(blank=True, max_length=400, null=True, verbose_name='Request address')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='Request parameter')),
                ('request_method', models.CharField(blank=True, max_length=64, null=True, verbose_name='Request method')),
                ('request_msg', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('request_ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='Request Ip')),
                ('request_browser', models.CharField(blank=True, max_length=64, null=True, verbose_name='Request browser')),
                ('response_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Request code')),
                ('request_location', models.CharField(blank=True, max_length=64, null=True, verbose_name='Request location')),
                ('request_os', models.CharField(blank=True, max_length=64, null=True, verbose_name='Request Os')),
                ('json_result', models.TextField(blank=True, null=True, verbose_name='Returned messages')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='user_create')),
            ],
            options={
                'verbose_name': 'Operation log',
                'verbose_name_plural': 'Operation log',
            },
        ),
        migrations.CreateModel(
            name='MessagePushUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Have you read')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('message_push', models.ForeignKey(db_constraint=False, help_text='notification', on_delete=django.db.models.deletion.CASCADE, related_name='messagepushuser_message_push', to='system.MessagePush', verbose_name='notification')),
                ('user', models.ForeignKey(db_constraint=False, help_text='user', on_delete=django.db.models.deletion.CASCADE, related_name='messagepushuser_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Notice Announcement and User Relationship',
                'verbose_name_plural': 'Notice Announcement and User Relationship',
            },
        ),
        migrations.AddField(
            model_name='messagepush',
            name='user',
            field=models.ManyToManyField(related_name='user', related_query_name='user_query', through='system.MessagePushUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LoginInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='Description', null=True, verbose_name='Description')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='The record was last modified by', max_length=255, null=True, verbose_name='editor')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Data attribution department')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('session_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Session ID')),
                ('browser', models.CharField(max_length=64, verbose_name='Browser')),
                ('ipaddr', models.CharField(blank=True, max_length=32, null=True, verbose_name='ip')),
                ('loginLocation', models.CharField(blank=True, max_length=64, null=True, verbose_name='Login location')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='Operation information')),
                ('os', models.CharField(blank=True, max_length=64, null=True, verbose_name='Operating system')),
                ('status', models.BooleanField(default=False, verbose_name='Login status')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='user_create')),
            ],
            options={
                'verbose_name': 'Login log',
                'verbose_name_plural': 'Login log',
            },
        ),
        migrations.CreateModel(
            name='DictDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='Description', null=True, verbose_name='Description')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='The record was last modified by', max_length=255, null=True, verbose_name='editor')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Data attribution department')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('dictLabel', models.CharField(max_length=64, verbose_name='Dictionary tag')),
                ('dictValue', models.CharField(max_length=256, verbose_name='Dictionary key')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('status', models.CharField(max_length=2, verbose_name='Dictionary status')),
                ('sort', models.CharField(max_length=256, verbose_name='Dictionary sort')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='Remark')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='user_create')),
                ('dict_data', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='system.DictData', verbose_name='Associative dictionary')),
            ],
            options={
                'verbose_name': 'Dictionary details',
                'verbose_name_plural': 'Dictionary details',
            },
        ),
        migrations.CreateModel(
            name='ConfigSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='Description', null=True, verbose_name='Description')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='The record was last modified by', max_length=255, null=True, verbose_name='editor')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Data attribution department')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('configName', models.CharField(max_length=64, verbose_name='parameter name')),
                ('configKey', models.CharField(max_length=256, verbose_name='Parameter key name')),
                ('configValue', models.CharField(max_length=256, verbose_name='Parameter key value')),
                ('configType', models.CharField(max_length=8, verbose_name='Whether built-in')),
                ('status', models.CharField(max_length=8, verbose_name='Parameter status')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='Remark')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='user_create')),
            ],
            options={
                'verbose_name': 'Parameter settings',
                'verbose_name_plural': 'Parameter settings',
            },
        ),
        migrations.CreateModel(
            name='CeleryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='Description', null=True, verbose_name='Description')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='The record was last modified by', max_length=255, null=True, verbose_name='editor')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Data attribution department')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='mission name', max_length=256, verbose_name='mission name')),
                ('func_name', models.CharField(help_text='Execution function name', max_length=256, verbose_name='Execution function name')),
                ('kwargs', models.TextField(help_text='Execution parameters', max_length=1024, verbose_name='Execution parameters')),
                ('seconds', models.CharField(max_length=8, verbose_name='Execution time')),
                ('status', models.BooleanField(default=False, verbose_name='Operating status')),
                ('result', models.TextField(help_text='Task return content', max_length=10240, verbose_name='Task result')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='user_create')),
            ],
            options={
                'verbose_name': 'celery',
                'verbose_name_plural': 'celery',
            },
        ),
    ]
