# Generated by Django 3.0.8 on 2021-10-17 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=40)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('vip', 'Vip'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('level', models.CharField(choices=[('level0', '0'), ('level1', '1'), ('level2', '2'), ('level3', '3'), ('level4', '4'), ('level5', '5')], default='level1', max_length=20)),
                ('coin', models.IntegerField(default=0)),
                ('card_story', models.IntegerField(default=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='userprofile/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
