# Generated by Django 3.0.8 on 2021-12-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211210_2258'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
