# Generated by Django 3.0.8 on 2021-11-03 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20211031_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='card_story',
            new_name='point',
        ),
    ]
