import os

REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')
CELERY_REDIS_DB = os.getenv('CELERY_REDIS_DB')

GENERAL_QUEUE = "general"
MARKET_MAKER_QUEUE = 'market_maker'
EXCHANGE_QUEUE = 'exchange'
ETHEREUM_QUEUE = 'Ethereum'
BITCOIN_QUEUE = 'Bitcoin'
TRON_QUEUE = 'Tron'
RIPPLE_QUEUE = 'Ripple'

RQ_QUEUES_NAME = (
    GENERAL_QUEUE, MARKET_MAKER_QUEUE, EXCHANGE_QUEUE, ETHEREUM_QUEUE, BITCOIN_QUEUE, TRON_QUEUE, RIPPLE_QUEUE
)

WORKER_NUMBERS = {
    GENERAL_QUEUE: 2,
    MARKET_MAKER_QUEUE: 10,
    EXCHANGE_QUEUE: 40,
    ETHEREUM_QUEUE: 8,
    BITCOIN_QUEUE: 1,
    TRON_QUEUE: 5,
    RIPPLE_QUEUE: 1
}

RQ_QUEUES = {
    k: {
        'HOST': REDIS_HOST,
        'PORT': REDIS_PORT,
        'DB': CELERY_REDIS_DB
    } for k in RQ_QUEUES_NAME
}
